### ISSUE TITLE
blastn 2.15 support

### ISSUE THREAD

**Issue by muffato** [sanger-tol/blobtoolkit#105]
When switching to blastn 2.15 (tried both `2.15.0--pl5321h6f7f691_0` and `_1`), there is this warning on _stderr_:

```console
The -taxids command line option requires additional data files. Please see the section 'Taxonomic filtering for BLAST databases' in https://www.ncbi.nlm.nih.gov/books/NBK569839/ for details.
```
which suggests we could be doing something wrong, but I can't find on <https://www.ncbi.nlm.nih.gov/books/NBK569839/#_usrman_BLAST_feat_Taxonomic_filtering_fo_> any information on making the option work.

In the source code `c++/src/algo/blast/blastinput/blast_args.cpp` I can find that the warning is printed whenever an exception is raised
```cpp
        try{ 
            tb.reset(new CTaxonomy4BlastSQLite());
        }    
        catch(CException &){
            LOG_POST(Warning << "The -taxids command line option requires additional data files. Please see the section 'Taxonomic filtering for BLAST databases' in https://www.ncbi.nlm.nih.gov/books/NBK569839/ for details.");
        }    
```
so it seems there really is something wrong, but I don't know what. It'd be great to get more information about that exception, what it means, where exactly it's raised, etc/.

I also tried downloading a recent NT databases and faced the same problem. Maybe we're missing some files ?

**Comment by tkchafin** [comment]
Just posting as I think this covers embedding the taxids in custom blastdbs, I can look in more detail when I get a chance later
https://www.ncbi.nlm.nih.gov/books/NBK569841/
https://www.ncbi.nlm.nih.gov/books/NBK569839/#usrman_BLAST_feat.Taxonomic_filtering_fo

**Comment by muffato** [comment]
We download the NR database from the NCBI and it should already contain the taxon IDs. The problem is that I had the impression that the error was only showing up with 2.15 (same database and same command-line otherwise). Let me find an example

**Comment by tkchafin** [comment]
tracking progress in JIRA but adding the solution here for posterity 

Apparently we need to stage the tax* files into the working dir. This seems to conflict with what the online docs say, but at least the solution on our end is simple. I'll patch the blastn module to copy these over

```(base) tc25@farm22-head2:~/blast$ history 9 | grep singularity
  506  history 9 | grep singularity
(base) tc25@farm22-head2:~/blast$ singularity exec -B /lustre,/nfs https://depot.galaxyproject.org/singularity/blast:2.16.0--hc155240_2 /bin/bash $PWD/command.sh
Using ./current/nt
```

**Comment by muffato** [comment]
🙌🏼
