### ISSUE TITLE
nf-core module: entrezdirect/esummary

### ISSUE THREAD

**Issue by alxndrdiaz** [sanger-tol/blobtoolkit#3]
Write [entrez-direct](https://www.ncbi.nlm.nih.gov/books/NBK179288/) nf-core module: entrezdirect/esummary ;  nf-core modules issue: [new module: entrezdirect/esearch #1831](https://github.com/nf-core/modules/issues/1831).

**Comment by alxndrdiaz** [comment]
Latest entrez-direct version: [16.2-0 Bioconda Package Index](https://bioconda.github.io/recipes/entrez-direct/README.html#package-entrez-direct).

**Comment by muffato** [comment]
The nf-core pull-request has been merged
